import { CountryCode } from "../types/campaign-create.types"

const MEXICO_MAX_CAMPAIGN_AMOUNT_USD = 150000
const CHILE_MAX_CAMPAIGN_AMOUNT_USD = 60000
const COLOMBIA_MAX_CAMPAIGN_AMOUNT_USD = 60000
const USA_MAX_CAMPAIGN_AMOUNT_USD = 200000

const MEXICO_MIN_CAMPAIGN_AMOUNT_USD = 70000
const CHILE_MIN_CAMPAIGN_AMOUNT_USD = 30000
const COLOMBIA_MIN_CAMPAIGN_AMOUNT_USD = 30000
const USA_MIN_CAMPAIGN_AMOUNT_USD = 90000
//SOFTCAPS
const MEXICO_SC_CAMPAIGN_AMOUNT_USD = 105000
const CHILE_SC_CAMPAIGN_AMOUNT_USD = 45000
const COLOMBIA_SC_CAMPAIGN_AMOUNT_USD = 45000
const USA_SC_CAMPAIGN_AMOUNT_USD = 150000
//HARDCAPS
const MEXICO_HC_CAMPAIGN_AMOUNT_USD = 135000
const CHILE_HC_CAMPAIGN_AMOUNT_USD = 55000
const COLOMBIA_HC_CAMPAIGN_AMOUNT_USD = 55000
const USA_HC_CAMPAIGN_AMOUNT_USD = 185000

export const MAX_AMOUNTS_BY_COUNTRY: Record<CountryCode, number> = {
  'MX': MEXICO_MAX_CAMPAIGN_AMOUNT_USD,
  'CL': CHILE_MAX_CAMPAIGN_AMOUNT_USD,
  'CO': COLOMBIA_MAX_CAMPAIGN_AMOUNT_USD,
  'US': USA_MAX_CAMPAIGN_AMOUNT_USD,
}
export const MIN_AMOUNTS_BY_COUNTRY: Record<CountryCode, number> = {
  'MX': MEXICO_MIN_CAMPAIGN_AMOUNT_USD,
  'CL': CHILE_MIN_CAMPAIGN_AMOUNT_USD,
  'CO': COLOMBIA_MIN_CAMPAIGN_AMOUNT_USD,
  'US': USA_MIN_CAMPAIGN_AMOUNT_USD,
}

export const SOFT_CAP_AMOUNTS_BY_COUNTRY: Record<CountryCode, number> = {
  'MX': MEXICO_SC_CAMPAIGN_AMOUNT_USD,
  'CL': CHILE_SC_CAMPAIGN_AMOUNT_USD,
  'CO': COLOMBIA_SC_CAMPAIGN_AMOUNT_USD,
  'US': USA_SC_CAMPAIGN_AMOUNT_USD,
}
export const HARD_CAP_AMOUNTS_BY_COUNTRY: Record<CountryCode, number> = {
  'MX': MEXICO_HC_CAMPAIGN_AMOUNT_USD,
  'CL': CHILE_HC_CAMPAIGN_AMOUNT_USD,
  'CO': COLOMBIA_HC_CAMPAIGN_AMOUNT_USD,
  'US': USA_HC_CAMPAIGN_AMOUNT_USD,
}
